# Generated by Django 3.2.13 on 2023-10-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
