# Generated by Django 3.2.13 on 2023-10-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='ArticleContent',
        ),
    ]
